// 🌊 this file is auto-generated by Fernando Rojo's script. don't edit it.
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";
const faMicrosoft = (props: SvgProps) => <Svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" width="brands" height="brands" {...props}><Path d="M0 32h214.6v214.6H0V32zm233.4 0H448v214.6H233.4V32zM0 265.4h214.6V480H0V265.4zm233.4 0H448V480H233.4V265.4z" /></Svg>;
export default faMicrosoft;