// 🌊 this file is auto-generated by Fernando Rojo's script. don't edit it.
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";
const faDiceFour = (props: SvgProps) => <Svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512" width="solid" height="solid" {...props}><Path d="M0 96C0 60.7 28.7 32 64 32H384c35.3 0 64 28.7 64 64V416c0 35.3-28.7 64-64 64H64c-35.3 0-64-28.7-64-64V96zm160 64a32 32 0 1 0 -64 0 32 32 0 1 0 64 0zM128 384a32 32 0 1 0 0-64 32 32 0 1 0 0 64zM352 160a32 32 0 1 0 -64 0 32 32 0 1 0 64 0zM320 384a32 32 0 1 0 0-64 32 32 0 1 0 0 64z" /></Svg>;
export default faDiceFour;