// 🌊 this file is auto-generated by Fernando Rojo's script. don't edit it.
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";
const faExclamation = (props: SvgProps) => <Svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 512" width="solid" height="solid" {...props}><Path d="M64 64c0-17.7-14.3-32-32-32S0 46.3 0 64V320c0 17.7 14.3 32 32 32s32-14.3 32-32V64zM32 480a40 40 0 1 0 0-80 40 40 0 1 0 0 80z" /></Svg>;
export default faExclamation;