// 🌊 this file is auto-generated by Fernando Rojo's script. don't edit it.
import * as React from "react";
import Svg, { SvgProps, Path } from "react-native-svg";
const faGenderless = (props: SvgProps) => <Svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 384 512" width="solid" height="solid" {...props}><Path d="M192 144a112 112 0 1 1 0 224 112 112 0 1 1 0-224zm0 288a176 176 0 1 0 0-352 176 176 0 1 0 0 352z" /></Svg>;
export default faGenderless;